version: '3.4'

services:
  metriclistener:
    image: listener:${LISTENER_VERSION}
    container_name: metriclistener
    restart: on-failure
    ports:
      - 7100:7100
      - 7101:7101
      - 7102:7102
      - 7103:7103
    volumes:
      - ./docFiles/metricListener.yaml:/etc/metricListener/metricListener.yaml
      - ./docFiles/public.pem:/etc/metricListener/public.pem
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - back-tier
    ports:
      - 9091:9090
    volumes:
      - ./docFiles/prometheus.yml:/prometheus-data/prometheus.yml
    command:  --config.file=/prometheus-data/prometheus.yml

networks:
  back-tier:
