---
authHeader: "X-Webpa-Signature"
authDelimiter: "="
webhookRequest:
  config:
    url: "http://listener-example:7100/endpoint"
    secret: "SECRET"
  events: [".*"]
  duration: "1m"
webhookRegistrationURL: "http://tr1d1um:6100/api/v3/hook"
webhookTimeout: "10s"
webhookRegistrationInterval: "1m"
port: ":7100"
endpoint: "/endpoint"
responseCode: 202