version: "3.8"
services:
  app:
    build: .
    ports:
      - "7100:7100"
    container_name: listener-example
    networks:
      - xmidt

networks:
  xmidt:
    external: true
    name: docker-compose_xmidt